#:kivy 1.0.9

<Grabber>:
    size: 24, 24
    canvas:
        Clear
        Color:
            rgba: 1, 1, 1, 1
        Ellipse:
            pos: self.center_x - 1, self.center_y - 1
            size: 12, 12
        Color:
            rgba: 0, 0, 1, 1
        Ellipse:
            pos: self.center_x, self.center_y
            size: 10, 10

<SimWidget>:
    Grabber:
        id: grabber1
        center: self.parent.center